---
title: "Model Building"
author: "Peter Chong"
output: github_document
---

```{r}
#Input files
df <- read.csv("/Users/wengliangchong/Desktop/RunTheData/MarathonData.csv", header = T, 
               stringsAsFactors = FALSE)
```

```{r}
set.seed(75652)
trainRows <- sample(75652, 60522)
train <- df[trainRows,]
test <- df[-trainRows,]
```

General Features:
Age, Gender, Temp, AgeGroup, Humid

Specific Pace Features:
X5ks, first5kpace, AgeGroupRelativePace, GenderRelativePace, GenderAndAgeGroupRelativePace


```{r}
fit <- lm(X42ks ~ Age+Gender+Temp+AgeGroup+Humid+X5ks+first5kpace, train)
summary(fit)
```
```{r}
pred <- predict(fit, newdata=test)
mean(test$X42ks-pred)
sd(test$X42ks-pred)
```




































```{r}
set.seed(75652)
sample(1:15652,1)
```

```{r}
df[8980, c("Gender", "Year", "AgeGroup")]
```

```{r}
Leg <- c("km 5-10", "km 10-15", "km 15-20", "km 20-25", "km 25-30", "km 30-35", "km 35-40", "km 40-42")
Color <- rep(c("Male", "Year 2015", "Age 45 ~ 54"), each=8)
Diff <- c()
for (i in 1:8) {
  Insert <- (df[8980,20+i]-mean(df[which(df$Gender == "Male"),20+i]))/mean(df[which(df$Gender == "Male"),20+1])
  Diff <- c(Diff, Insert)
}
for (i in 1:8) {
  Insert <- (df[8980,20+i]-mean(df[which(df$Year == 2015),20+i]))/mean(df[which(df$Year == 2015),20+1])
  Diff <- c(Diff, Insert)
}
for (i in 1:8) {
  Insert <- (df[8980,20+i]-mean(df[which(df$AgeGroup == "45 ~ 54"),20+i]))/mean(df[which(df$AgeGroup == "45 ~ 54"),20+1])
  Diff <- c(Diff, Insert)
}
x <- data.frame("Leg" = rep(Leg,3), "Diff" = Diff, "Color" = Color)
```

```{r}
ggplot(data=x, aes(x=Leg, y=Diff, fill=Color, color=Color)) + ylab("Runner's Hubris Difference") +
  geom_bar(stat="identity",position=position_dodge(), alpha=0.5) + theme(legend.position = c(0.9, 0.85)) +
  scale_x_discrete(limits=Leg) + scale_y_continuous(limits=c(-4.2,2))
```

```{r}
ggplot(df, aes(Age, as.POSIXct(Net.Time,format="%H:%M:%S"))) +
  geom_point(color = "#4E84C4", alpha=0.3) + ylab("Net Finish Time") + 
  stat_smooth(method = "lm", formula = y ~ poly(x,2), color="#D16103")
```


















































































































